machine:
  datacenter-id: 0
  worker-id: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:oauth_role;INIT=RUNSCRIPT FROM 'classpath:db/init.sql'
        username: root
        password:
        min-idle: 2
        initial-size: 1
        max-total: 5
        max-wait-millis: 200
        connectProperties: { connectionInitSqls: SET NAMES utf8mb4 }
    rules:
      sharding:
        default-database-strategy:
          standard:
            sharding-column: id
            sharding-algorithm-name: custom_inline
        default-key-generate-strategy:
          column: id
          key-generator-name: custom_key_generator
        key-generators:
          custom_key_generator:
            type: MyShardingKeyGenerator
            props:
              custom_datacenter_id: ${machine.datacenter-id}
              custom_worker_id: ${machine.worker-id}
        sharding-algorithms:
          custom_inline:
            type: INLINE
            props:
              algorithm-expression: ds0
